# Generated by Django 2.2.17 on 2020-12-31 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingtransaction_dropoff2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtransaction',
            name='dropoff2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff2', to='location.MapLocation'),
        ),
    ]
