# Generated by Django 2.2.17 on 2020-12-31 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('booking', '0008_bookingtransaction_dropoff7'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff10', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff11', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff12', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff13', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff14', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff15', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff16', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff17', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff18', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff19', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff20', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff21', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff22', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff23', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff24', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff25', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff26',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff26', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff27',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff27', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff28',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff28', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff29',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff29', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff30',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff30', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff31',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff31', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff32',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff32', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff33',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff33', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff34',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff34', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff35',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff35', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff36',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff36', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff37',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff37', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff38',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff38', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff39',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff39', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff40',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff40', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff8', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff9', to='location.MapLocation'),
        ),
    ]
