# Generated by Django 2.2.17 on 2020-12-31 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('booking', '0010_auto_20201231_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff51',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff51', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff52',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff52', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff53',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff53', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff54',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff54', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff55',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff55', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff56',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff56', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff57',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff57', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff58',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff58', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff59',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff59', to='location.MapLocation'),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='dropoff60',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingtransaction_dropoff60', to='location.MapLocation'),
        ),
    ]
